name: Translate Discord Bot

on:
    push:
        branches: ["main"]

jobs:
    push_to_registery:
        name: Push docker to image
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: rasitozgun/translate-bot

            - name: Build and push Docker image
              uses: docker/build-push-actions@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  lebal: ${{ steps.meta.outputs.labels }}
