name: Build Docker image

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x]
        steps:
            - name: Set up Checkout
              uses: actions/checkout@v4
              with:
                  path: main
            - name: Build docker image
              run: docker build . --file Dockerfile translate-bot:latest
